# Site settings
title: Jax Blog
SEOTitle: Jax Blog
header-img: img/home-bg.jpg
email: 185772455@qq.com
description: "你所关注的, 就是你的世界"
keyword: "你看那朵乌云儿"
url: "https://Jax1993.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     3128048007
zhihu_username:     wang-er-9-77
github_username:    Jax1993
twitter_username:   Wjh2333
#facebook_username:  wjh
#linkedin_username:  wjh



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: Jax1993

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一个人只拥有此生此世是不够的，<br>他还应该拥有诗意的世界."
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Pornhub",
        href: "https://www.pornhub.com"
    },
    {
        title: "XVideo",
        href: "https://www.xvideos.com"
    },
    {
        title: "91porn",
        href: "http://91porn.com/index.php"
    },
    {
        title: "sq1.xyz",
        href: "http://sq1.xyz" 
    },
    {
        title: "xnxx",
        href: "https://www.xnxx.com"
    },
    {
        title: "xhamster",
        href: "https://xhamster.com"
    },
    {
        title: "ObjC 中国",
        href: "https://www.objccn.io"
    },
    {
        title: "Hi-Mike",
        href: "https://himike.win"
    },
    {
        title: "Aaron",
        href: "https://shuimu.org"
    }
]
